[package]
name = "natlint"
version = "0.1.0-alpha"
edition = "2021"
license = "MIT"
repository = "https://github.com/srdtrk/natlint"
description = "A linter for Solidity natspec comments."

[dependencies]
clap = { version = "4.5", default-features = true, features = ["derive"] }
anyhow = "1.0"
